name: API Performance Tests

on:
  push:
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install K6
        run: |
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
          k6 version

      - name: Prepare reports folder
        run: mkdir -p k6-reports

      - name: Run K6 performance test
        run: |
          mkdir -p k6-reports
          k6 run scenarios/index.js --vus 500 --duration 300s --out json=k6-reports/k6-report.json


      - name: Upload K6 report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: k6-reports
