name: API Performance Tests

on:
  push:
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:grafana/stable
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Prepare reports folder
        run: mkdir -p k6-reports

      - name: Run K6 performance test
        run: |
          mkdir -p k6-reports
          k6 run k6-tests/index.js --vus 500 --duration 300s --out json=k6-reports/k6-report.json


      - name: Upload K6 report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: k6-reports
